<?xml version="1.0" encoding="utf-8"?><Database Name="QLTSBK" Class="QLTSDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-VU1US43;Initial Catalog=QLTSBK;Integrated Security=True" SettingsObjectName="QuanLyTaiSanDHBK.Properties.Settings" SettingsPropertyName="QLTSBKConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.TaiSan" Member="TaiSans">
    <Type Name="TaiSan">
      <Column Name="MaTaiSan" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaLoaiTaiSan" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MaPhong" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TenTaiSan" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MaChungTuTang" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ThongSoKyThuat" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ThanhTien" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SoLuong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SoLuongNhap" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TyLeHM" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TyLeCL" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NgayGhiTang" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NoiDung" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="GhiChu" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="TaiSan_ChungTuGiam" Member="ChungTuGiams" ThisKey="MaTaiSan" OtherKey="MaTaiSan" Type="ChungTuGiam" />
      <Association Name="Phong_TaiSan" Member="Phong" ThisKey="MaPhong" OtherKey="MaPhong" Type="Phong" IsForeignKey="true" />
      <Association Name="LoaiTaiSan_TaiSan" Member="LoaiTaiSan" ThisKey="MaLoaiTaiSan" OtherKey="MaLoaiTaiSan" Type="LoaiTaiSan" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Phong" Member="Phongs">
    <Type Name="Phong">
      <Column Name="MaPhong" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenPhong" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MaKhoa" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="Phong_TaiSan" Member="TaiSans" ThisKey="MaPhong" OtherKey="MaPhong" Type="TaiSan" />
      <Association Name="Khoa_Phong" Member="Khoa" ThisKey="MaKhoa" OtherKey="MaKhoa" Type="Khoa" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.LoaiTaiSan" Member="LoaiTaiSans">
    <Type Name="LoaiTaiSan">
      <Column Name="MaLoaiTaiSan" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenLoaiTaiSan" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="LoaiTaiSan_TaiSan" Member="TaiSans" ThisKey="MaLoaiTaiSan" OtherKey="MaLoaiTaiSan" Type="TaiSan" />
    </Type>
  </Table>
  <Table Name="dbo.Khoa" Member="Khoas">
    <Type Name="Khoa">
      <Column Name="MaKhoa" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenKhoa" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="Khoa_Phong" Member="Phongs" ThisKey="MaKhoa" OtherKey="MaKhoa" Type="Phong" />
    </Type>
  </Table>
  <Table Name="dbo.ChungTuGiam" Member="ChungTuGiams">
    <Type Name="ChungTuGiam">
      <Column Name="MaChungTuGiam" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaTaiSan" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SoLuong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NgayGhiGiam" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ThanhTien" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NoiDung" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="GhiChu" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="TaiSan_ChungTuGiam" Member="TaiSan" ThisKey="MaTaiSan" OtherKey="MaTaiSan" Type="TaiSan" IsForeignKey="true" />
    </Type>
  </Table>
</Database>